### ISSUE TITLE
Is there a release coming any time soon

### ISSUE THREAD

**Issue by patrickklaeren** [hardcodet/wpf-notifyicon#48]
I've looked at the various comments in discussions around this repo - .NET Core and .NET 5 support have been added and there hasn't been a release of this package in what is now over four years.

The work has been done but there isn't even a preview to test? I understand there may be trepidation in terms of breaking/backward compat, but keeping a release this long when the programming has been done is arbitrary.

If you need help - I am more than available in this regard.

When can we expect a release here?

cc @punker76 @Lakritzator

**Comment by Lakritzator** [comment]
Hi Patrick,

first, I'm just a contributor to this project as the original maintainer currently has other priorities.
Which is fine, Philipp did a great job, where we can build upon.

I think you don't mean it badly, but this is the worst question maintainers can get.
You might know this from your projects... but at least it seems you have way more time on your hands that I have.

I myself work on software when I have time, and feel like it.
Now with the pandemic, and having a kid/wife/dog, I hardly have ANY time left.
I either work, or spend time with my kid who is unfortunately not the easiest and while we cannot entertain him in indoor playgrounds, go to the movies or do other stuff, we have him at home most of the time. By the time he sleeps, daddy is dead tired.

And if I do develop something, my current gear is so damn slow that I feel agitated and give up.

The answer to your "nagging", because that is what it sounds like (well it's true!!), is:
It comes when it comes, and due to me answering this question, it will at least take a week longer. Because I usually only have time to work on things like this, once a week.

About not having a preview, we just didn't get to it yet.
We "recently" added a CI, but previews are not yet on our list.

If you are very depending on this, you are more than welcome to help.

Here are some options:
* You can help by cloning the project (develop branch) & building it in VS2019. In "src\NotifyIconWpf\bin\Debug" you will find the nuget package. Point your project to it, and see if it does what it needs to do. If not create a detailed bug report, or send a PR.
* Stop nagging, it saves me time from answering. 😀 
* Or you can sponsor me, via github sponsoring. It might help me a bit towards a new laptop, which will definitively motivate me. But I can fully understand if you don't like to sponsor someone who says what he thinks 🤷‍♂️ 

Btw... if I would be at work, where I get payed for my work, I might be able to give you an estimate when "you" can expect a release. Mainly because the time I'm at work is plannable. As I am not, the answer is: I don't have a clue.

That is probably not the answer you were hoping for, but at least I had a bit of time to write one 😉 

Best wishes,
Robin

**Comment by patrickklaeren** [comment]
I'm not sure what has prompted this bitter response. I assume you may not have been part of an open source project before.

I am not sure how one issue equates to nagging. You have repeatedly said, prior to August there would be a release. People are dependent on this project - if the work has been done, it is quite simple to provide an update, especially if someone else wants to help and they want to ensure they do not do the same work that has already been done.

Given this response I believe it better to fork and move away from what you consider nagging.

**Comment by punker76** [comment]
@patrickklaeren This will be available with next release (v1.1.0), coming hopefully soon. We still have to clarify who can upload the NuGet package. But after this, it should be done quickly. Thx 🙏

**Comment by patrickklaeren** [comment]
> @patrickklaeren This will be available with next release (v1.1.0), coming hopefully soon. We still have to clarify who can upload the NuGet package. But after this, it should be done quickly. Thx 🙏

An actual reply, much appreciated.

**Comment by Lakritzator** [comment]
@patrickklaeren you are right, I have not been a part of open soure project before.
I didn't find my response that bitter, but I guess one should not write the truth and it also depends with what mindset your read it.

I mentioned that you asked the most unfavorite question, told you why I can't give an answer to when I can provide a release. Also that the biggest thing that is open is testing. Time is preventing me to do this, so I told you how you can assist there. This is actually a thing which @punker76 didn't reflect in his answer. I think he means that he will see how we can deliver a preview.

Maybe you can show how you would have answered when you can't give an satisfying answer to a question which has been asked before?
